### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by vivekgalatage** [dicksonleong/Tweetian#10]
Let me first congratulate you on the awesome application tweetian. Its really great to have the native application with fluid performance. I have a suggestion for improving the user experience.

When opening Tweetian, it shows the unread tweets since last time of opening Tweetian. This is really good feature of staying at the tweet opened in the last session.

Assume that you opened Tweetian some 5-6 days ago and now you have some 300+ tweets which are to be read. So in order to visit the top of the tweets, the user needs to scroll the entire list which is painful. Consider that when not using the Tweetian, the user might have used some other means of visiting twitter on the web browser on desktop etc. so the 300+ tweets he has already visited. 

It would be a great feature if the Tweetian can provide the option "Scroll to top" directly instead of scrolling until the top.

Thanks once again.

PS: I am using tweetian on Nokia N8.

**Comment by dicksonleong** [comment]
It is already there. Just click on the tab button above, it will scroll to top.

**Comment by vivekgalatage** [comment]
oh wow! great. Thanks for pointing out.
