### ISSUE TITLE
Update for Instagram previews

### ISSUE THREAD

**Issue by hugovk** [dicksonleong/Tweetian#12]
The Instagram client used to use short URLs like http://instagr.am/p/B7Pde/ and Tweetian showed a preview and the image could be opened.

Now nearly all the URLs I see from the client are like http://instagram.com/p/B7Pde/ and no preview is shown. The only choice is to open the URL in the browser, and their webpages don't show properly in any of the three browsers on my phone.

Please could you add support for the new URL format? The old should be kept in case anyone still has the old client, or in case anyone shares an old URL.

**Comment by dicksonleong** [comment]
Done in commit 6ee4defacb20e14cb4c1a2a05b1174afa3937948, I just haven't release the update yet

**Comment by hugovk** [comment]
Great! Any ETA on a release?

(I see you removed the old format. I guess it won't be a problem, I don't think I've seen any since old ones for a while now.)

**Comment by dicksonleong** [comment]
not sure yet, but I don't want to release an update just for this fix.
