### ISSUE TITLE
Text can't be pasted into Tweetian

### ISSUE THREAD

**Issue by denseacat** [dicksonleong/Tweetian#13]
Noticed hour ago.
I can copy text FROM field, but can't paste it into it from another place, e.g. from SMS or notes.
Nokia C7 00, with all updates, if this does matter.

Looks like copy\paste properly works again, after rebooting.

**Comment by dicksonleong** [comment]
I can't reproduce this problem, but even if I can reproduce, I can't fix it anyway, because the clipboard is handle by the system and Qt, but not me.
