### ISSUE TITLE
Fixed imagehosting selection

### ISSUE THREAD

**Issue by denseacat** [dicksonleong/Tweetian#14]
When attaching a photo to tweet, i see a button below,[Service] that allows to change image destination(Twitter, twitPic,etc). 
I think it will be good idea, add new option in settings, describing Tweetian behavior.
Something like this
**Options > Main > Images**
- Show "select" button with bottom bar
- Ask me everytime and hide "select" button with bar
- Choose service where pictures wil be uploaded to, AND show "select" button with bar
- Choose service where pictures wil be uploaded to, AND hide "select" button with bar

Select once and forget about it.
Actually, i'd wanted to request only last line :)

**Comment by dicksonleong** [comment]
Done in 61ca616348740212ddf847337ff73393863e7602
