### ISSUE TITLE
Message Input field is too small on Nokia C7 00 Symbian^3 Belle, latest updates

### ISSUE THREAD

**Issue by denseacat** [dicksonleong/Tweetian#15]
Hello @dicksonleong , i have an bug issue, when i tapping on text field, between it and virtual keyboard appears unused blank space. In portrait mode this space appears too.

![updscreenshotapp1](https://f.cloud.github.com/assets/3787889/512527/ab193b60-be2a-11e2-8b92-899d8ae68198.jpg)
![updscreenshotapp2](https://f.cloud.github.com/assets/3787889/512528/ab3aa3cc-be2a-11e2-8ed0-339f1dd99062.jpg)

**Comment by dicksonleong** [comment]
The space is for auto completer for mentions. When you type "@" the auto completer will appear. I don't think it is good to keep adjust the height when auto complete is appear/disappear

**Comment by denseacat** [comment]
Better add font size adjustment ability instead/
