### ISSUE TITLE
Strings translated on Transifex but not on the application

### ISSUE THREAD

**Issue by air-dex** [dicksonleong/Tweetian#3]
I was looking at the French translation on the Symbian version of Tweetian. I saw some expressions which were not translated (see attachments). I go to Transifex to verify their translations but they were completed and correct.

Here are the attachments. Twwetian's language is supposed to be "French" :

![SC001](https://f.cloud.github.com/assets/3170439/38651/7d928204-54f9-11e2-8643-a7bddd91e384.JPG)

"Retour" should be written instead of "Back".

![SC002](https://f.cloud.github.com/assets/3170439/38652/7d92a3ec-54f9-11e2-8acc-5660630e0d8f.JPG)

"Quitter" should be written instead of "Exit".

![SC003](https://f.cloud.github.com/assets/3170439/38668/65f6af7a-54fa-11e2-9791-848ad02eeb0d.JPG)

"En réponse à" should be written instead of "In reply to" and "Réponse" should be written instead of "Reply". There are also encoding problems for arrows.

I will update the issue if I find other untranslated strings on Tweetian which are translated correctly on Transifex.

More info :
Tweetian version : 1.7 for Symbian
Device : Nokia N8-00 with Nokia Belle

**Comment by dicksonleong** [comment]
Thanks for reporting. It seem that I forget to make some of the text for translation. Will be fixed soon.

**Comment by dicksonleong** [comment]
Fixed in commit cd102b13d0fa4db1a993e13afda718a44bfc8477
