### ISSUE TITLE
Very slow shutdown

### ISSUE THREAD

**Issue by klonuo** [dicksonleong/Tweetian#30]
When I exit Tweetian, I have to wait 10-30 sec, to be able to access my phone.

Nokia N8

**Comment by hugovk** [comment]
A workaround would be to send the app to the background to do it's shutdown and let you get on with it. But I doubt we're going to see much if any updates here.

You could try Settings -> Refresh cache, in case that helps.

**Comment by klonuo** [comment]
Ok, thanks
