### ISSUE TITLE
"Azure Market Place Translator Subscription associated with the request credentials has zero balance"

### ISSUE THREAD

**Issue by hugovk** [dicksonleong/Tweetian#6]
When translating Finnish tweets I got:

TranslateApiException: The
Azure Market Place Translator
Subscription associated with the request
credentials has zero balance. :
ID=3010.V2_Json.Translate.2501BDC2

If a free quota is used up, there's not much to do about it. 

But perhaps Symbian/MeeGo versions could use different API keys, if they're not already.

(And maybe the error message could be replaced with something less cryptic.)

**Comment by dicksonleong** [comment]
Yes, the monthly free quota of the translation service is used up. It will be reset in the next few days.

In the next version, a message will show up saying that the translation limit is reached. See commit 8a2b90dde6ba5cb7c56a33a952c0e0e5df84465e.

**Comment by vishalsingh1234** [comment]
TranslateApiException: The Azure Market Place Translator Subscription associated with the request credentials has zero balance. : ID=3541.V2_Json.Translate.3EA0BDF5

**Comment by vishalsingh1234** [comment]
TranslateApiException: The Azure Market Place Translator Subscription associated with the request credentials has zero balance. : ID=3541.V2_Json.Translate.3EA0BDF5

**Comment by tejmishra4** [comment]
TranslateApiException: The Azure Market Place Translator Subscription associated with the request credentials is not in an active state. : ID=3627.V2_Json.Translate.48DB25E4

**Comment by tejmishra4** [comment]
TranslateApiException: The Azure Market Place Translator Subscription associated with the request credentials is not in an active state. : ID=3627.V2_Json.Translate.48DB25E4

**Comment by tejmishra4** [comment]
ID=3944.V2_Json.Translate.49DD7748

**Comment by tejmishra4** [comment]
TranslateApiException: The Azure Market Place Translator Subscription associated with the request credentials is not in an active state. : ID=3427.V2_Json.Translate.4BA8D521
