### ISSUE TITLE
Add support for Flickr URLs that don't include "www."

### ISSUE THREAD

**Issue by hugovk** [dicksonleong/Tweetian#8]
Currently Tweetian supports (for preview and opening the image) two types of Flickr links, shortened and shortened:
- \- http://flic.kr/p/{base-58-encoded-photo-id}
- \- http://www.flickr.com/photos/{user-id}/{photo-id}/

Sometimes people share "unshortened" Flickr links without the "www.".
- \- http://flickr.com/photos/{user-id}/{photo-id}/

It would be good to show these images in Tweetian too.

(I've seen these links coming from the Twitter for Android client, but I don't know if it just how the user pasted in the link. Anyway, they seem common enough, a rough estimate from Google searches (e.g.: site:twitter.com "http://www.flickr.com/photos") suggests:
- About 4,590,000 results for http://www.flickr.com/photos
- About 962,000 results for http://flic.kr/p
- About 654,000 results for http://flickr.com/photos

This suggests the www-less version is roughly 10.5% of the total.

**Comment by hugovk** [comment]
See: https://github.com/dicksonleong/Tweetian/pull/9

**Comment by dicksonleong** [comment]
Added in commit 115bbf69910824329d7e850a6dc6ce4b6e3a8de4
